os: Visual Studio 2017
version: "{branch}-{build}"

environment:
 PY_PYTHON: 3.7-32

clone_depth: 1

install:
 - git submodule update --init

build_script:
 - py -3.7-32 -m pip install -U pip
 - py -3.7-32 -m pip install pipenv
 - py -3.7-32 -m pipenv install
 - py -3.7-32 -m pipenv run python -m scons source
 - 7z a -tzip -r output\nvda-py3.zip source Pipfile Pipfile.lock nvda-py3.cmd
 
artifacts:
 - path: output\*
