os: Visual Studio 2017
version: "{branch}-{build}"

environment:
 PY_PYTHON: 3.7-32

clone_depth: 1

install:
 - git submodule update --init

build_script:
 - ps: |
     py -3.7-32 -m pip install -U pip
     py -3.7-32 -m pip install pipenv
     py -3.7-32 -m pipenv install
     mkdir output
     py -3.7-32 -m pipenv run python source\nvda.pyw 2> output\error.txt

artifacts:
 - path: output\*
